- lastname: Assari
  firstname: Ryan
  type: PHD
  email: maa154 at sfu dot ca
  image: RyanAssari.jpg
  intro: Ryan received a B.Sc. in Physics and a B.Sc. in Computer Engineering from Amirkabir University of Technology in 2019 and 2020, respectively. He completed an M.Sc. in Computing Science at Simon Fraser University in 2024 under the supervision of Prof. Qianping Gu. His research interests include graph algorithms, multi-agent systems, and reinforcement learning. More information can be found on his <a href="https://ryan-assari.github.io/" target="_blank">homepage</a>.
  webpage: https://ryan-assari.github.io/
  github: https://github.com/ryan-assari
  linkedin: https://www.linkedin.com/in/ryan-assari/

- lastname: Mao
  firstname: Zining
  type: PHD
  email: zander_mao at sfu dot ca
  image: ZiningMao.jpg
  intro: Zining received a B.Sc. in Computer Science from New York University Shanghai in 2021 and an M.Sc. in Computing Science from our lab at Simon Fraser University in 2025. He is interested in reinforcement learning and multi-agent systems.

- lastname: Sun
  firstname: Dingyi
  type: PHD
  email: dingyi_sun at sfu dot ca
  image: DingyiSun.jpg
  intro: Dingyi received a B.Eng. in Electrical Engineering and Automation from Huazhong University of Science and Technology in 2018 and an M.S. in Electrical and Computer Engineering (Robotics Track) from the University of Michigan in 2020. He is interested in path planning, machine learning, and robotic perception.

- lastname: Tan
  firstname: Jiaqi
  type: PHD
  email: jiaqi_tan at sfu dot ca
  intro: Jiaqi received a B.Eng. in Computer Science and Technology from Shenzhen University in 2019 and an M.Sc. in Computing Science from Simon Fraser University in 2022.
  github: https://github.com/ChristinaTan0704

- lastname: Tang
  firstname: Jingtao
  type: PHD
  email: jingtao_tang at sfu dot ca
  image: JingtaoTang.jpg
  intro: Jingtao received a B.Eng. and an M.S., both in Software Engineering from East China Normal University, in 2018 and 2021, respectively. His research interests include planning and scheduling, multi-agent systems, combinatorial optimization, and machine learning. More information can be found on his <a href="https://reso1.github.io/blog/" target="_blank">homepage</a>.
  webpage: https://reso1.github.io/blog/
  github: https://github.com/reso1
  google_scholar: https://scholar.google.com/citations?user=58xSbH8AAAAJ

- lastname: Yang
  firstname: Lufan
  type: PHD
  email: lufan_yang at sfu dot ca
  intro: Lufan received a B.Eng. in Flight Vehicle Design and Engineering from Dalian University of Technology in 2020 and an M.Eng. in Aeronautical and Astronautical Science and Technology from Zhejiang University in 2023.
  google_scholar: https://scholar.google.com/citations?user=LpByMzgAAAAJ

- lastname: Yang
  firstname: Yifan
  type: PHD
  email: yifan_yang_6 at sfu dot ca
  intro: Yifan received a B.Eng. and an M.Eng., both in Computer Science and Technology from Harbin Institute of Technology, in 2020 and 2024, respectively.
  google_scholar: https://scholar.google.com/citations?user=HCVkMcgAAAAJ

- lastname: Chamani
  firstname: Danoosh
  type: F_MSC
  image: DanooshChamani.jpg
  intro: Danoosh received a B.Sc. in Computer Software Engineering from the University of Tehran in 2019 and an M.Sc. in Computing Science from Simon Fraser University in 2022. He is interested in reinforcement learning, machine learning, and robotics.
  linkedin: https://www.linkedin.com/in/danoosh-chamani-64903b207
  positions:
    - Data Scientist at Scotiabank
    - Data Scientist at Health Canada

- lastname: Li
  firstname: Baiyu
  type: F_MSC
  image: BaiyuLi.jpg
  intro: Baiyu received a B.Eng. in Computer Science from Northeastern University (Shenyang, China) in 2020 and an M.Sc. in Computing Science from Simon Fraser University in 2023. He is interested in path planning, multi-agent system, and parallel computing.
  linkedin: https://www.linkedin.com/in/baiyu-li-07494318b/
  positions:
    - Embedded Software Developer at Fortinet
    - Backend Software Engineer at TikTok
    - Embedded Software Developer at Fortinet

- lastname: Lin
  firstname: Qiushi
  type: F_MSC
  image: QiushiLin.jpg
  intro: Qiushi received a B.Eng. in Computer Science and Technology from Southern University of Science and Technology in 2020 and an M.Sc. in Computing Science from Simon Fraser University in 2023. He is interested in machine learning, reinforcement learning, and multi-agent system.
  github: https://github.com/Qiushi-Lin/
  positions:
    - Ph.D. Student at Simon Fraser University

- lastname: Samuel
  firstname: Ervin
  type: F_MSC
  email: esa95 at sfu dot ca
  image: ErvinSamuel.jpg
  intro: Ervin received a B.Sc. in Computer Science from National Tsing Hua University in 2022 and an M.Sc. in Computing Science from Simon Fraser University in 2025. He is interested in artificial intelligence, particularly reinforcement learning and its application to path planning.
  linkedin: https://www.linkedin.com/in/ervinsamuel/

- lastname: Xu
  firstname: Qinghong
  type: F_MSC
  image: QinghongXu.jpg
  intro: Qinghong received a B.S. in Computational Mathematics from Xiamen University in 2017 and an M.S. in Computational and Applied Mathematics in 2019 and an M.Sc. in Computing Science in 2022, both from Simon Fraser University. She is interested in multi-agent systems, path planning, and machine learning.
  linkedin: https://www.linkedin.com/in/qinghong-jackie-xu
  positions:
    - Software Development Engineer at Amazon

- lastname: Zhong
  firstname: Xinyi
  type: F_MSC
  image: XinyiZhong.jpg
  intro: Xinyi received a B.C.S. Honours in Computer Science from Carleton University in 2019 and an M.Sc. in Computing Science from Simon Fraser University in 2021. She is interested in path planning, multi-agent system, and robotics.
  linkedin: https://www.linkedin.com/in/xinyi-zhong-3802b5203
  positions:
    - Software Development Engineer at Amazon

- lastname: Chen
  firstname: Jialiang
  type: F_UNDERGRAD

- lastname: Ma
  firstname: Ziyuan
  type: F_UNDERGRAD
  intro: Ziyuan received a B.Sc. in Computing Science from Simon Fraser University in 2020. He was an undergraduate research student in our lab in 2020/2021.
  github: https://github.com/ZiyuanMa

- lastname: Zheng
  firstname: Xiaoye
  type: F_UNDERGRAD

- lastname: Luo
  firstname: Yudong
  type: F_VISITOR
  image: YudongLuo.jpg
  intro: Yudong received a B.Eng. in Computer Science from Shanghai Jiao Tong University in 2018 and an M.Sc. in Computing Science from Simon Fraser University in 2020. He is interested in reinforcement learning, machine learning, and multi-agent system. Yudong visited our lab for 12 months in 2020/2021. More information can be found on his <a href="http://miyunluo.com" target="_blank">homepage</a>.
  webpage: http://miyunluo.com
  google_scholar: https://scholar.google.com/citations?user=1xPjAucAAAAJ
  positions:
    - Postdoctoral Researcher at HEC Montréal
    - Ph.D. Student at University of Waterloo
